### ISSUE TITLE
fix : audio listeners in the scene 해결 부탁드립니다.

### ISSUE THREAD

**Issue by BiteSnail** [bokob/Open_Start#1]
현재 IndoorNavigation Scene에서 audio listeners in the scene가 두 명이 있다는 오류가 계속해서 발생합니다.

topdowncamera에 audio listener 컴포넌트 제거 부탁드립니다!

**Comment by bokob** [comment]
해결했습니다.

**Comment by BiteSnail** [comment]
확인했습니다. 감사합니다.
