### ISSUE TITLE
층별 구분 없는 목적지 문제점

### ISSUE THREAD

**Issue by BiteSnail** [bokob/Open_Start#10]
이번에 목적지를 json파일로 불러오는 작업을 하시면서 3층과 4층 목적지가 모두 표시되는 문제점이 발생했습니다. 그래서 이걸 해결해야 할 것 같은데, 스크립트를 바꿀지 혹은 맵 데이터를 겹쳐서 하나로 만들지 고민입니다.
위 이미지에서 계단부분을 실제로 구현하면 층별로 warp하지 않아도 작동할 것 같습니다! 
![image](https://user-images.githubusercontent.com/55152597/185822313-51de54f3-c656-45c8-9628-56110e9367bb.png)

1) 스크립트를 수정한다.
2) 맵 데이터를 수정한다.

선택해 주시면 감사하겠습니다.

**Comment by bokob** [comment]
스크립트 수정보다는 맵 데이터 겹쳐서 해볼까요

**Comment by BiteSnail** [comment]
한번 해보겠습니다 ㅋㅋ 계단 만들기가 관건이네요

**Comment by BiteSnail** [comment]
fe6cab0d8be24d05b0178f2e4138e668ffee833d 에서 구현 완료하였습니다.

계단은 stair라는 이름의 prefab형식으로 저장해 놓았습니다. 다만 계단형식으로 만드는 것이 아닌 평평한 판 상태로 만드는 것이 좀 더 효율적일 것이라는 생각이 듭니다. 추후에 수정한 버전도 올리겠습니다.

**Comment by BiteSnail** [comment]
미니맵은 플레이어의 높이로부터 1m 높이로 적용시켰습니다. 
이를 위해서 topdowncamera 관련 스크립트를 추가하였습니다. 단순 위치만 조정하는 스크립트 이긴하나 조금 더 조정이 필요할 것이라고 생각합니다.
