### ISSUE TITLE
층 바꿀 때 QR 코드 버튼 자동 눌림

### ISSUE THREAD

**Issue by bokob** [bokob/Open_Start#3]
![image](https://user-images.githubusercontent.com/85085804/184066781-7417baa2-dfb5-4ea4-8d4c-c675d0b8414b.png)

층 바꿀 때 QR 코드 찍어야 해서 자동으로 되게끔 만드신 건가요?

![image](https://user-images.githubusercontent.com/85085804/184066901-5405a89e-39a5-4a67-82e1-47f2a42165e4.png)

**Comment by BiteSnail** [comment]
엥 제가 만든 함수가 아니라서 잘 모르겠네요 ㅋㅋ ;;
근데 층 바꿀 때 그냥 위치 변경 때문에 있는 함수 아닌가요??

**Comment by bokob** [comment]
밑에거 잘못 가져왔네요
불용 4번 영상보니까 해결 가능할 듯

**Comment by BiteSnail** [comment]
해결해 보겠습니다 도전

**Comment by BiteSnail** [comment]
해당 문제는 SetQrCodeRecenterTarget()함수에서 OnQr()함수가 있어서 발생한 문제였습니다. QR코드 ON/OFF기능 만들 때 발생한 버그로 보입니다. 해결한 것은 풀리퀘스트 올리겠습니다.

**Comment by bokob** [comment]
풀리퀘 승인하겠습니다.
